IF NOT EXISTS(SELECT * 
               	FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = 'puzzles')
BEGIN
CREATE TABLE puzzles (id INTEGER PRIMARY KEY, date VARCHAR(10) NOT NULL);
INSERT INTO puzzles (id, date) VALUES (1028, '2024-04-12');
END

IF NOT EXISTS(SELECT * 
               	FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = 'solves')
BEGIN
CREATE TABLE solves (id INTEGER IDENTITY(1, 1) PRIMARY KEY, puzzle_id INTEGER NOT NULL, name VARCHAR(max) NOT NULL);
END

IF NOT EXISTS(SELECT * 
               	FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = 'solve_rows')
BEGIN
CREATE TABLE solve_rows (id INTEGER IDENTITY(1, 1) PRIMARY KEY, solve_id INTEGER NOT NULL, row VARCHAR(max) NOT NULL);
END